language: php

php:
  - "7.1"

jobs:
  include:
    - stage: test
      services:
        - mysql
      before_script:
        - cp .env.travis .env
        - curl -LO https://s3-eu-west-1.amazonaws.com/aplus.travis/dump-13-07-17.sql
        - curl -LO https://s3-eu-west-1.amazonaws.com/aplus.travis/workingDays.json
        - mv workingDays.json ./storage/app/
        - mysql -e 'create database insurance_test;'
        - mysql -u root insurance_test < dump-13-07-17.sql
        - composer self-update
        - composer install --no-interaction
        - php artisan key:generate
      script:
        - vendor/bin/phpunit
    - stage: codestyle
      before_script:
        - composer self-update
        - composer install --no-interaction
        - curl -LO https://s3-eu-west-1.amazonaws.com/aplus.travis/aplus-cs.zip
        - unzip aplus-cs.zip -d $TRAVIS_BUILD_DIR/Aplus
        - php vendor/bin/phpcs --config-set installed_paths $TRAVIS_BUILD_DIR/Aplus
      script:
        - php vendor/bin/phpcs --standard=Aplus ./
